language: python
dist: xenial
python:
  - "3.6"
  - "3.7.0"
  - "3.7.1"
  - "3.7.2"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pipenv install --dev
script:
  - pipenv run python -m doctest -v marshmallow_dataclass/*.py
  - cd docs && pipenv run make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master