name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    container: docker://altendky/hydra:latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        toxenv:
          - py36,report,codecov
          - py37,report,codecov
          - py38,report,codecov
          - pypy3,report,codecov
          - doc
          - check
    steps:
      - uses: actions/checkout@v1
      - run: |
          eval "$(pyenv init -)"
          pip install tox
          tox -v -e "${{ matrix.toxenv }}"
        name: tox
